name: opsd_time_series

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pandas
  - numpy
  - xlrd  # pandas: excel i/o
  - openpyxl  # pandas: excel i/o
  - bottleneck  # accelerates some pandas operations
  - numexpr  # accelerates some pandas operations
  - jupyter  # jupyter notebook
  - pyyaml
  - requests
  - jupyter_contrib_nbextensions  # nice add-ons for jupyter
  - selenium  # required to scrape URLs from Terna website
  - paramiko  # for sftp access to ENTSO-E Transparency
